### ISSUE TITLE
cimni clupa gerna cu'u la'o zi pegjs@0.10.0 zi

### ISSUE THREAD

**Issue by lynn** [guskant/gerna_cipra#8]
.i mi troci lo nu pilno la'o zi **zantufa-1.3.js.peg** zi jo'u la'o zi **nodejs** zi jo'u la'o zi **pegjs@0.10.0** zi (noi ninrai fo lai peg)

.i proga fa mu'a la'e di'e

```js
var peg = require("pegjs");
var fs = require("fs");
var parser = peg.generate(fs.readFileSync("zantufa-1.3.js.peg").toString());
```

.i ku'i la peg cu pante fo la'e di'e

```
C:\code\tergihu\node_modules\pegjs\lib\compiler\passes\report-infinite-recursion.js:42
        throw new GrammarError(
        ^
GrammarError: Possible infinite loop when parsing (left recursion: text -> intro_null -> su_clause -> erasable_clause -> bu_clause_no_pre -> bu_tail -> BU_clause -> BU_pre -> pre_clause -> si_clause -> erasable_clause).
    at rule_ref (C:\code\tergihu\node_modules\pegjs\lib\compiler\passes\report-infinite-recursion.js:42:15)
    at visit (C:\code\tergihu\node_modules\pegjs\lib\compiler\visitor.js:10:35)
    at C:\code\tergihu\node_modules\pegjs\lib\compiler\visitor.js:26:17
    at Object.each (C:\code\tergihu\node_modules\pegjs\lib\utils\arrays.js:63:7)
    at C:\code\tergihu\node_modules\pegjs\lib\compiler\visitor.js:25:16
    at visit (C:\code\tergihu\node_modules\pegjs\lib\compiler\visitor.js:10:35)
    at C:\code\tergihu\node_modules\pegjs\lib\compiler\passes\report-infinite-recursion.js:32:9
    at Object.every (C:\code\tergihu\node_modules\pegjs\lib\utils\arrays.js:87:12)
    at sequence (C:\code\tergihu\node_modules\pegjs\lib\compiler\passes\report-infinite-recursion.js:31:14)
    at visit (C:\code\tergihu\node_modules\pegjs\lib\compiler\visitor.js:10:35)
```

.i va'o lo nu mi pilno la'o zi **pegjs@0.8.0** zi gi'e basygau zoi zi **buildParser** zi zoi zi **generate** zi kei,

```js
var peg = require("pegjs");
var fs = require("fs");
var parser = peg.buildParser(fs.readFileSync("zantufa-1.3.js.peg").toString());
// snada .i ku'i...
var tree = parser.parse("ko'a broda mi");
```

.i .uanai fliba fa la'o zi parse zi secu'u di'e

```
undefined:60008
          if (arg[v].length != 0)
                     ^

TypeError: Cannot read property 'length' of undefined
    at _node_int (eval at compile (C:\code\tergihu\node_modules\pegjs\lib\compiler.js:57:29), <anonymous>:60008:22)
    at _node_int (eval at compile (C:\code\tergihu\node_modules\pegjs\lib\compiler.js:57:29), <anonymous>:60009:23)
    at _node (eval at compile (C:\code\tergihu\node_modules\pegjs\lib\compiler.js:57:29), <anonymous>:59997:16)
    at peg$c87 (eval at compile (C:\code\tergihu\node_modules\pegjs\lib\compiler.js:57:29), <anonymous>:122:42)
    at peg$parsesu_valsi (eval at compile (C:\code\tergihu\node_modules\pegjs\lib\compiler.js:57:29), <anonymous>:7925:14)
    at peg$parsesu_clause (eval at compile (C:\code\tergihu\node_modules\pegjs\lib\compiler.js:57:29), <anonymous>:7731:14)
    at peg$parseintro_null (eval at compile (C:\code\tergihu\node_modules\pegjs\lib\compiler.js:57:29), <anonymous>:692:14)
    at peg$parsetext (eval at compile (C:\code\tergihu\node_modules\pegjs\lib\compiler.js:57:29), <anonymous>:609:12)
    at Object.parse (eval at compile (C:\code\tergihu\node_modules\pegjs\lib\compiler.js:57:29), <anonymous>:60062:18)
    at Object.<anonymous> (C:\code\tergihu\src\app.js:6:19)
```

.i .u'u .a'o xu do jimpe ja ba'o lifri tu'a lo srenoi?

.i .ei mi pilna mo'oi versiio be la'o zi pegjs zi do'e la zantufa?

ki'e!

**Comment by guskant** [comment]
u'u lo ve farvi cu mo'a moi i ba'anai la cirko pu zu stika la ilmentufa tezu'e lo nu sarxe lo ca se farvi be la nodejys kei i ca bo mi lazni
i mi ba lanli la nodejys pe la zantufa i u'u ka'e ku lo pi so'i si'e cu temci fi lo mu'e mulno
